"""Initial migration - users, members, bookings, recurring patterns

Revision ID: f2f547987da9
Revises: 
Create Date: 2026-01-31 20:59:18.380649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f547987da9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique user identifier'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address for login"),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt-hashed password'),
    sa.Column('role', sa.Enum('MEMBER', 'ADMIN', name='userrole'), nullable=False, comment='User role for authorization'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the account is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When the user registered'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last modification time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique member identifier'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Associated user account'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="Member's full name"),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Contact phone number'),
    sa.Column('membership_status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='membershipstatus'), nullable=False, comment='Current membership status'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='Admin who approved this member'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Approval timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Registration timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_members_membership_status'), 'members', ['membership_status'], unique=False)
    op.create_table('recurring_patterns',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique pattern identifier'),
    sa.Column('member_id', sa.UUID(), nullable=False, comment='Member who owns this pattern'),
    sa.Column('pattern_type', sa.Enum('DAILY', 'WEEKLY', name='patterntype'), nullable=False, comment='daily or weekly recurrence'),
    sa.Column('days_of_week', sa.ARRAY(sa.Integer()), nullable=False, comment='Days of week for weekly patterns (0=Sun, 6=Sat)'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Start time of day for bookings'),
    sa.Column('duration_mins', sa.Integer(), nullable=False, comment='Duration of each booking in minutes'),
    sa.Column('valid_from', sa.Date(), nullable=False, comment='First date pattern applies'),
    sa.Column('valid_until', sa.Date(), nullable=False, comment='Last date pattern applies'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether pattern is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When pattern was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_patterns_is_active'), 'recurring_patterns', ['is_active'], unique=False)
    op.create_index(op.f('ix_recurring_patterns_member_id'), 'recurring_patterns', ['member_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique booking identifier'),
    sa.Column('member_id', sa.UUID(), nullable=False, comment='Member this booking is for'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Booking start time'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='Booking end time'),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='bookingstatus'), nullable=False, comment='Current booking status'),
    sa.Column('recurring_pattern_id', sa.UUID(), nullable=True, comment='Recurring pattern that generated this booking'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created this booking'),
    sa.Column('cancelled_by', sa.UUID(), nullable=True, comment='User who cancelled this booking'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='When the booking was cancelled'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When the booking was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurring_pattern_id'], ['recurring_patterns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_member_id'), 'bookings', ['member_id'], unique=False)
    op.create_index(op.f('ix_bookings_recurring_pattern_id'), 'bookings', ['recurring_pattern_id'], unique=False)
    op.create_index(op.f('ix_bookings_start_time'), 'bookings', ['start_time'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_recurring_pattern_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_member_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_recurring_patterns_member_id'), table_name='recurring_patterns')
    op.drop_index(op.f('ix_recurring_patterns_is_active'), table_name='recurring_patterns')
    op.drop_table('recurring_patterns')
    op.drop_index(op.f('ix_members_membership_status'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
